apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: nodestatistics.addons.k8s.leopoldxx.io
spec:
  group: addons.k8s.leopoldxx.io
  names:
    kind: NodeStatistic
    plural: nodestatistics
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            replicas:
              format: int64
              type: integer
          required:
          - replicas
          type: object
        status:
          properties:
            deployment:
              type: object
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
